// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrdbfftygfsksfcfjsqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZGJmZnR5Z2Zza3NmY2Zqc3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDcwODksImV4cCI6MjA2MDIyMzA4OX0.JK1ZV7w2707Lgkev-oWezjMsC0F_Uk0tQ-082mhzYwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);